name: portfolio
description: Portfolio developed in flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  dynamic_height_grid_view: ^0.0.4
  easy_localization: ^3.0.3
  easy_logger: ^0.0.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.4.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.5
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/screenshots/
    - assets/translations/
    - assets/fonts/
